name: goes-pm25-dnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - xarray
  - zarr
  - fsspec
  - s3fs
  - gdown
  - matplotlib
  - cartopy
  - tensorflow
  - keras
  - scikit-learn
  - requests
  - beautifulsoup4
  - tqdm
  - netcdf4
  - pip
  - pip:
      - pysolar
